src/cell.rs, src/cell/tests.rs
The cell implementation did not correctly grow the memory to store its header when initialized with a default value of size 0.
=> fix: correctly grow memory on values of size 0

Cargo.lock, examples/Cargo.lock, src/lib.rs, src/reader.rs, src/reader/tests.rs, src/writer.rs, src/writer/tests.rs
This PR adds a reader and a writer implementation (both buffered and unbuffered) to facilitate stable memory interactions that happen sequentially in stable memory. In particular, the reader and writer keep track of the offset and grow stable memory on the fly as required.
=> feat: Implement reader and writer

src/storable.rs
Update the way integers are serialized/deserialized to use big-endian bytes rather than little-endian. That way, the byte representations of these numbers are sorted, which is a very desirable property.
I asked all the current users of `stable-structures` and none are using these encodings yet, so this should be a safe breaking change.
=> BREAKING CHANGE: change `Storable` encoding of integers from le to be

Cargo.lock, Cargo.toml, examples/src/basic_example/src/lib.rs, examples/src/custom_types_example/src/lib.rs, src/file_mem.rs, src/lib.rs
An implementation of `Memory` that is backed up by a file. This is very useful to read stable structures that have been serialized to a file on disk.
=> feat: reading stable structures from a file

examples/Cargo.lock, examples/Cargo.toml, examples/README.md, examples/dfx.json, examples/src/basic_example/candid.did, examples/src/basic_example/src/lib.rs, examples/src/custom_types_example/src/lib.rs, examples/src/vecs_and_strings/Cargo.toml, examples/src/vecs_and_strings/candid.did, examples/src/vecs_and_strings/src/lib.rs, examples/test.sh, src/btreemap.rs, src/btreemap/iter.rs, src/lib.rs, src/storable.rs
BTreeMap currently take the maximum size of the BTreeMap as arguments. Example:
```
let map: StableBTreeMap<_, Key, Value> = StableBTreeMap::init(memory, MAX_KEY_SIZE, MAX_VALUE_SIZE)
```
One issue with this API is that specifying the max sizes is independent of the type being used, and that poses a couple of usability issues:
1.  If you're using a primitive type as your key/value (e.g. `u64`), it's not obvious what size you should put as an argument. The correct answer is `8`, because the `Storable` implementation of `u64` serializes it to a vector of 8 bytes, but that's far from obvious.
2. It's easy to put an incorrect value by accident if you're managing a few stable structures. I already made this mistake in the bitcoin canister.
A more safe and clear implementation is that the `Key` …
=> chore: Enhancements to the StableBTreeMap API.

examples/Cargo.lock, examples/Cargo.toml, examples/dfx.json, examples/src/quick_start/Cargo.toml, examples/src/quick_start/README.md, examples/src/quick_start/candid.did, examples/src/quick_start/candid.old.did, examples/src/quick_start/src/lib.rs, examples/src/quick_start/src/memory.rs, examples/test.sh
Adds an example that developers can use as a starting point for their projects, showcasing
the very common use-case of wanting to store part of the state in stable structures and other parts on the heap.
=> feat: add quickstart example

src/storable.rs
It's clearer to make developers explicitly specify whether or not a type is fixed or variable in size.
With new optimizations that we'll be doing to `BTreeMap`, variable sized elements can end up having a smaller memory footprint. If we assume by default that a type is fixed in size, developers won't benefit from this optimization.
=> fix: do not make `BoundedStorable` fixed size by default

src/storable.rs, src/storable/tests.rs
This change introduces more storable types:
1. Byte arrays `[u8; N]`.
2. Variable-sized byte arrays of limited capacity `Blob<CAP>`.
3. Tuples (A, B) where both components are storable.
=> feat: add more (bounded) storable types

examples/src/basic_example/src/lib.rs, examples/src/custom_types_example/src/lib.rs, examples/src/quick_start/src/lib.rs, examples/src/vecs_and_strings/src/lib.rs, src/btreemap.rs, src/btreemap/allocator.rs, src/btreemap/iter.rs, src/cell.rs, src/cell/tests.rs, src/log.rs, src/log/tests.rs, src/vec.rs, src/vec/tests.rs
This change changes the order of the type arguments in BTreeMap to be more consistent with other data structures and with the standard library (Allocators are the last type arguments in Rust).
=> refactor(btreemap): change the type argument order

examples/src/custom_types_example/src/lib.rs, examples/src/vecs_and_strings/src/lib.rs, src/btreemap.rs, src/btreemap/iter.rs, src/cell.rs, src/storable.rs, src/storable/tests.rs, src/vec.rs, src/vec/tests.rs
This change modifies the `Storable::from_bytes` method to accept `Cow<[u8]>` instead of a byte vector. Often, a storable type does not need to own the original byte array (the exceptions are only `Vec<u8>` and `String`).
There are a few places (such as iterators) where we can eliminate unnecessary byte array clones with this optimization.
The new signature is also more symmetrical:
`T::from_bytes(t.to_bytes())` becomes valid code.
=> refactor(storable): eliminate unnecessary buffer clones

src/lib.rs, src/log.rs, src/log/tests.rs
With this change, the Log type has an explicit Storable type argument instead of working with raw bytes.
This interface is more convenient and consistent with other data structures.
=> feat(log): make the stable log typed

examples/src/vecs_and_strings/src/lib.rs, src/btreemap.rs, src/btreemap/iter.rs, src/btreemap/node.rs, src/storable.rs
This change replaces the `range` method based on prefixes with a `range` method based on key range, similarly to the `BTreeMap::range` from the standard library.
To achieve this, we:
1. Require map keys to implement Ord.
2. Store node keys decoded.
3. Store the key bounds in the map iterator.
I also separated keys and values into separate arrays, because it makes the code a bit cleaner and usually a bit more efficient.
=> feat(btreemap): implement proper range scan

src/log.rs, src/log/tests.rs, src/storable.rs, src/vec.rs, src/vec/tests.rs
This change adds iterator implementations for StableLog and StableVec. The vectors support random access, so iterating over a slice of items will not required decoding a prefix of a stable structure.
=> feat(log, vec): implement random-access iterators

examples/src/basic_example/src/lib.rs, examples/src/custom_types_example/src/lib.rs, examples/src/quick_start/src/lib.rs, examples/src/vecs_and_strings/src/lib.rs, src/btreemap.rs, src/btreemap/iter.rs
`BTreeMap::insert` returned an `InsertError` if the key/value inserted was too large. Now that keys/values are required to implement `BoundedStorable`, the only scenario where an `InsertError` can be triggered is if the implementation of `Storable` and/or `BoundedStorable` for the key/value has a bug.
This commit changes the API to remove the `InsertError`, replacing it with a precondition that assumes that the implementations of `Storable`/`BoundedStorable` are correct. This has the advantage that the API is now cleaner, and panicking whenever we detect a bug in the implementation is safer for the developer.
=> chore(btreemap): remove errors from 'insert' API

Cargo.lock, src/memory_manager.rs
Problem:
When loading a `MemoryManager`, the code asserts that the bucket size is equal to the `BUCKET_SIZE_IN_PAGES` constant. In practice, this makes upgrading to 0.4.0 from previous versions fail, given that the `BUCKET_SIZE_IN_PAGES` has been changed.
Solution:
Remove the assertion, as it is no longer required.
=> fix(memorymanager): remove unneeded assertion

src/log.rs, src/log/tests.rs, src/vec.rs
On the Wasm32 architecture, usize is 32 bit, making it impossible for the log to report correct size in bytes on large data sets.
This commit changes the types of indices and lengths in Vec and Log so that they will behave correctly if these structures grow beyond four billion items.
=> fix(log, vec): use u64 for indices and lengths

benchmarks/Cargo.lock, benchmarks/build.sh, benchmarks/dfx.json, benchmarks/run.sh, benchmarks/src/btreemap.rs, benchmarks/src/memory_manager.rs
The benchmarks we have aren't comprehensive enough to get an accurate picture of the performance of `BTreeMap`. For example, in the `0.4.0` release, the benchmarking numbers showed us an improvement of ~40% in the `insert` and `remove` operations, but when I profiled the Bitcoin canister with that upgrade I saw a _regression_ of about 40%.
Add more thorough benchmarks for `insert`, `remove`, and `get` to get a more accurate picture of the performance impact of our changes. These will then be used to address the performance regressions we've seen with `0.4.0+`
=> feat: add benchmarks for BTreeMap

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/btreemap.rs, src/btreemap/node.rs, src/btreemap/proptests.rs
This change adds new methods to the StableBTreeMap interface:
1. clear() removes everything from the map.
2. first_key_value() returns the entry with the smallest key.
3. last_key_value() returns the entry with the largest key.
=> feat(btreemap): add methods to get first/last entry

src/storable.rs, src/storable/tests.rs
This commit fixes a bug in storable tuple encoding panicking on variable-size entries fitting into u16.
=> fix: encoding of tuples with u16 entries

src/storable.rs, src/storable/tests.rs
This change adds Storable and BoundedStorable implementations for floating-point types.
=> feat: make floats storable

src/btreemap.rs, src/btreemap/node.rs, src/btreemap/proptests.rs
This change introduces a new btree map method, `iter_upper_bound`. It returns an iterator pointing to the first element that is less than the given key.
We need this method for the time series API because we need to find the closest keys to the left and to the right of the given key. We can do the latter with the `range` API, but the former requires a new method.
We took inspiration from experimental API in BTreeMap: https://doc.rust-lang.org/nightly/std/collections/struct.BTreeMap.html#method.upper_bound
=> feat(btreemap): add iter_upper_bound api

Cargo.toml, benchmark-canisters/Cargo.lock
The path for benchmarks needs to be explicitly specified, otherwise `cargo publish` fails.
=> chore: setup path for benchmarks

src/storable.rs
This change introduces implementations of `Storable` and `BoundedStorable` traits for the `std::cmp::Reverse` type.
=> feat: make Reverse<T> storable

src/btreemap.rs, src/btreemap/iter.rs, src/btreemap/node.rs, src/btreemap/proptests.rs
This commit lays some of the groundwork for EXC-1395, which is to support variable-length keys and values in the BTreeMap.
The code that is specific to the node containing a fixed number of elements is abstracted away from the `BTreeMap` and into the `Node` itself. Once the concept of a node is completely abstracted, then we can drop in a new implementation of Node that supports a variable number of entries.
As part of this abstraction:
* Some of the fields/constants in `node.rs` are made private. Follow-up commits will make all fields in the `Node` private.
* Some tests were rewritten to be more generic, but still offers the same or better coverage.
=> refactor: generalize the `Node` in `BTreeMap`

benches/benches.rs, benches/run-benchmark.sh, benchmark-canisters/src/btreemap.rs, benchmark-canisters/src/vec.rs
Benchmarks are run within a canister to obtain the instruction count. However, benchmarks can run for up to 5B instructions in case of queries, and 50B in case of updates. We do have benchmarks that we haven't been able to run because they surpass these limits.
Use `drun` instead of `dfx` to run the benchmarks. `drun` can be configured to have a practically infinite instruction count. As a result, a few benchmarks are now enabled by this commit, and all the benchmarks are now query calls to avoid side effects.
Closes EXC-1405
=> fix: use drun for running the benchmarks.

src/btreemap.rs, src/btreemap/iter.rs, src/btreemap/node.rs, src/btreemap/proptests.rs
Continues the refactor in #74 by making all the fields in the `Node` private.
=> refactor: make all fields in BTreeMap Node private

src/btreemap.rs
When running the tests, Rust would show the following warning:
```
warning: reference to packed field is unaligned
```
This commit fixes the underlying issue causing these warnings.
=> chore: fix warning about unaligned field references

benchmark-canisters/src/btreemap.rs, src/btreemap.rs
A minor performance optimization where we avoid loading the same node twice when removing a key. Our benchmarks show a ~35% performance improvement in the `btreemap_remove_*` benchmarks.
```
btreemap_remove_blob_4_1024
time:   [1291.5 M Instructions 1291.5 M Instructions 1291.5 M Instructions]
change: [-35.542% -35.542% -35.542%] (p = 0.00 < 0.05)
Performance has improved.
btreemap_remove_blob_8_1024
time:   [1482.7 M Instructions 1482.7 M Instructions 1482.7 M Instructions]
change: [-35.194% -35.194% -35.194%] (p = 0.00 < 0.05)
Performance has improved.
btreemap_remove_blob_16_1024
time:   [1663.2 M Instructions 1663.2 M Instructions 1663.2 M Instructions]
change: [-35.169% -35.169% -35.169%] (p = 0.00 < 0.05)
Performance has improved.
btreemap_remove_blob_32_1024
time:   [1713.5 M …
```
=> perf: remove redundant node load from BTreeMap::remove

src/lib.rs
This change introduces a new constant, MAX_PAGES, indicating the maximum number of pages a canister can address. This constant is useful for constructing a restricted memory that can span up to the last page of the base memory.
```rust
RestrictedMemory::new(memory, 16..MAX_PAGES)
```
=> feat: add a constant for the max number of pages

src/types.rs
This is a micro optimization where we no longer require `Bytes` to have a `packed` representation. This allows the Rust compiler to remove the overhead of this type completely during the compilation process. The net result is that performance improves by ~3% all around, and almost by %5 in some cases. Not bad for a one-line optimization.
```
btreemap_insert_blob_4_1024
time:   [902.82 M Instructions 902.82 M Instructions 902.82 M Instructions]
change: [-3.0126% -3.0126% -3.0126%] (p = 0.00 < 0.05)
Performance has improved.
btreemap_insert_blob_8_1024
time:   [1040.8 M Instructions 1040.8 M Instructions 1040.8 M Instructions]
change: [-2.8112% -2.8112% -2.8112%] (p = 0.00 < 0.05)
Performance has improved.
btreemap_insert_blob_16_1024
time:   [1136.5 M Instructions 1136.5 M Instructions …
```
=> perf: do not makes `Bytes` packed.

.gitignore
I use Jetbrains which displays its config files as git diff. This PR adds common editor ignore entries to `.gitignore`.
=> chore: Ignore Jetbrains and VSCode config files

Cargo.lock, examples/Cargo.lock, examples/src/basic_example/Cargo.toml, examples/src/custom_types_example/Cargo.toml, examples/src/quick_start/Cargo.toml, examples/src/vecs_and_strings/Cargo.toml
Few (24) days ago a new version of [ciborium](https://crates.io/crates/ciborium) was released.
Therefore we can use the official dependency in the quickstart example instead of referencing a particular commit.
In addition, this PR bumps the candid and ic-* dependencies of the examples as provided by @ielashi.
=> chore: update dependencies in examples

src/base_vec.rs, src/lib.rs, src/vec.rs, src/vec/tests.rs
This change factors StableVec functionality into an internal BaseVec type parameterized over the stable structure magic number.
The motivation is to re-use the BaseVec code in more specialized array-like data structures, such as binary heaps and certified sequences.
Note: this PR has no functional changes, it only moves the code around.
=> refactor(vec): move Vec logic into BaseVec

.github/workflows/ci.yml, CHANGELOG.md, README.md, examples/Cargo.lock, examples/Cargo.toml, examples/dfx.json, examples/src/task_timer/Cargo.toml, examples/src/task_timer/candid.did, examples/src/task_timer/src/lib.rs, src/lib.rs, src/min_heap.rs, src/min_heap/tests.rs
This change introduces the `MinHeap` stable structure analogous to `std::collections::BinaryHeap`.
Contrary to `BinaryHeap`, `MinHeap` prioritizes smaller items, which I found much more useful in practice than prioritizing larger items.
=> feat: stable min heap data structure

CHANGELOG.md, Cargo.lock, Cargo.toml, examples/Cargo.lock
We've introduced a new min heap data structure in #91, and this version makes it accessible to our users.
=> chore: upgrade version to 0.5.5

src/tests.rs, src/vec.rs
The refactoring of `vec` accidentally made `vec::InitError` private, which broke clients that upgraded to the latest stable structures release. See issue #98.
This commit makes `vec::InitError` public, and adds a test to ensure it always remains public.
=> fix: make `vec::InitError` public again

Cargo.lock, Cargo.toml, README.md, examples/Cargo.lock
Bumping the version is needed to roll out the fix in #100.
=> chore: bump version to 0.5.6

Cargo.lock, Cargo.toml, src/btreemap/node.rs, src/btreemap/node/tests.rs, src/btreemap/node/v1.rs
A new version of `Node` will soon be introduced, and this commit paves the way for that by:
1. Moving the logic of `load` and `store` into a separate file (`v1.rs`)
2. Adding a proptest for `load` and `store` to ensure we don't introduce regressions
=> test: `Node::load` and `Node::save`

src/btreemap.rs
Hi @ielashi,
I'm not sure but, is it possible that the init of a new `BTreeMap::new` in `init_v2` is incorrect in your PR and should be replaced with `BTreeMap::new_v2`?
At least, while testing your PR, I was facing following error which seems to be resolved by tweaking those.
> 2023-08-26 14:42:36.677876 UTC: [Canister by6od-j4aaa-aaaaa-qaadq-cai] Panicked at 'Cannot get max size of unbounded type.', /Users/daviddalbusco/.cargo/git/checkouts/stable-structures-10185dfe005f3b12/8620b4f/src/storable.rs:450:9
=> fix: init_v2 BTreeMap::new

.github/workflows/ci.yml, benches/benches.rs, benches/run-benchmark.sh, benchmark-canisters/dfx.json, benchmark-canisters/src/btreemap.rs, examples/dfx.json, src/btreemap.rs, src/btreemap/node.rs, src/btreemap/node/tests.rs, src/btreemap/node/v1.rs, src/btreemap/node/v2.rs, src/btreemap/proptests.rs
This commit introduces V2 of BTreeMap which supports unbounded keys and values.
* V2 so far is intended only for beta testing and should not be used in any production setting. By default, BTreeMaps are using V1. V2 nodes are available only when initializing a BTreeMap with `init_v2` or `new_v2`. In the future, V1 maps will be migrated automatically to V2.
* Tests are updated to run for both V1 and V2 versions of the map.
* Benchmarks now include both V1 and V2. V2 is significantly slower at the moment per the benchmarking results below, but optimizations to follow on this PR will narrow that gap.
```
btreemap_insert_blob_4_1024
time:   [914.81 M Instructions 914.81 M Instructions 914.81 M Instructions]
change: [+0.1085% +0.1085% +0.1085%] (p = 0.00 < 0.05)
Change within noise threshold. …
```
=> feat: BTreeMap V2 (beta)

benchmark-canisters/src/btreemap.rs, benchmarks/benchmark.rs, benchmarks/results.yml, src/btreemap.rs
The page size used by the BTreeMap dictates how big the chunks are that are allocated. The smaller the page size, the more chunks that need to be allocated to store the same amount of data, and consequently the more reads and writes are required to load/save each node. On the other hand, a large page size also can incur additional memory overhead, so we need to be careful to not set it too high.
To explore this, I added a benchmark that stores 200 10MiB vectors in a BTreeMap. I tested different page sizes to explore its effect on both memory and instructions.
When using a larger pages size, from 1KiB to 20MiB, this is the best increase in performance I had seen:
(relative performance is measured against the base line of `page_size = 500`)
```
Benchmark: btreemap_insert_10mib_values …
```
=> perf: update BTreeMap v2 default page size from 500 bytes to 1024 bytes

benchmarks/results.yml, src/btreemap.rs, src/btreemap/node.rs
I did an analysis on how big node entries are. A node can have at most 11 entries, but ~70% of nodes contain <= 8 entries. With that information, I was able to reduce the page size in BTreeMap V2 in the case where the keys and values are both bounded, resulting in a storage saving of ~25%.
The report, generated by our new benchmarking framework, clearly shows the gains. V2 benchmarks saw a decline in the number of stable pages needed without compromising performance.
```
Benchmark: btreemap_insert_10mib_values
measurements:
instructions: 278228334 (0.00%) (no change)
node_load_v2: 10377468 (0.00%) (no change)
node_save_v2: 245958554 (0.00%) (no change)
stable_memory_size: 33 (0.00%) (no change)
---------------------------------------------------
Benchmark: btreemap_insert_blob_4_1024 …
```
=> perf: reduce storage requirements for bounded btreemaps by ~25%.

src/log.rs, src/log/tests.rs
This change introduces a stable log iterator that can enumerate entries in stable log stored in a thread-local variable.
This simplifies dealing with stable logs a lot; currently, clients have to replicate the same logic for each log, see ckBTC for example[^1].
[^1]: https://github.com/dfinity/ic/blob/712910487fe14924cb80622af47b31210cab95bc/rs/bitcoin/ckbtc/minter/src/storage.rs#L37
=> feat(log): add an iterator over thread-local log

benchmarks/benchmark.rs, benchmarks/results.yml, src/btreemap/node.rs, src/btreemap/node/io.rs, src/btreemap/node/reader.rs, src/btreemap/node/tests.rs, src/btreemap/node/v2.rs
When saving a BTreeMap V2 node, a large buffer was allocated where we first serialize the node, and then at a later stage we break this buffer into smaller pages and write those into stable memory. This was simpler to implement, yet inefficient.
This PR removes the large buffer allocation and instead uses a `NodeWriter`, which write the node incrementally without the need to allocate large buffers on the heap.
This narrows the performance gap even further between v1 and v2 as seen by the following benchmark report.
```
---------------------------------------------------
Benchmark: memory_manager_baseline
measurements:
instructions: 1176576551 (0.00%) (no change)
stable_memory_size: 8000 (0.00%) (no change)
---------------------------------------------------
Benchmark: …
```
=> perf: [BTreeMap V2] avoid allocating large buffer on save.

benchmarks/results.yml, src/btreemap.rs, src/btreemap/node/v1.rs, src/btreemap/node/v2.rs, src/storable.rs, src/storable/tests.rs
This commit adds a new method, `to_bytes_checked`, to the `Storable` trait. It includes assertions to detect if the `Storable` implementation of an element is buggy. This addresses the issue in #125, where a user had a mistake in their implementation of Storable, but it wasn't clear from the error that this was the case.
BTreeMap has been updated to use `to_bytes_checked` rather than `to_bytes`.
=> feat: add additional assertions to the `Storable` trait.

src/btreemap.rs, src/btreemap/node.rs, src/btreemap/node/tests.rs, src/btreemap/node/v1.rs, src/btreemap/node/v2.rs
Prior to this commit, the caller of `Node::load` needed to specify the node version that will be loaded. This is acceptable if all nodes have the same version, but given that a BTreeMap may have different versions of nodes (migration will be introduced in subsequent commits), this needs to change such that the node's version is detected on load.
=> refactor: determine node version automatically on load

src/storable.rs
Exposes some helper methods that are useful for developers. I found these useful as I was migrating the Bitcoin Canister to BTreeMap V2.
=> feat: expose helper methods for extracting bounds

src/btreemap/proptests.rs
Uses the `test_strategy` crate in declaring the proptests. The main advantage of this crate is that code formatting continues to work. With the traditional proptest macro formatting doesn't work anymore.
=> refactor: rewrite BTreeMap proptests using `test_strategy`.

src/btreemap.rs, src/cell.rs, src/log.rs
This pull request aims to improve the error-handling mechanism of the codebase by providing more descriptive error messages. It involves changes across multiple files (`cell.rs`, `log.rs`) to add implementations for the `fmt::Display` trait for `InitError`.
1. **Consistent Formatting**: Replaced `std::fmt` with `fmt` to maintain consistency in the code.
- File: `btreemap.rs`
2. **Enhanced Error Messages for `InitError` in `cell.rs`**: 
- Describes errors related to incompatible versions and value sizes.
3. **Detailed Error Messages for `InitError` in `log.rs`**: 
- Explains issues with incompatible data and index versions, as well as invalid indices.
Better error messages enhance the debugging experience and allow developers to understand the issues quickly, thereby saving time and …
=> feat: Improve Error Handling by Adding Display Implementations

src/btreemap.rs, src/btreemap/proptests.rs
Adds a fuzz test that can run indefinitely comparing the results of a stable BTreeMap to a standard BTreeMap.
I ended up using `proptest` rather than the conventional `cargo fuzz` for two reasons:
1. `cargo fuzz` requires nightly rust.
2. With proptest, we can have a short version of the fuzz test that runs as part of CI (which is included in this commit).
=> feat: comprehensive fuzzing for BTreeMap

src/btreemap.rs, src/btreemap/node/v2.rs, src/storable.rs
#142 introduced some utility methods in the `Bound` struct. We had copies of these utility methods elsewhere, which are no longer needed and are removed in this commit.
=> chore: remove redundant utility methods

benchmarks/results.yml, src/btreemap.rs
We'd like to support developers changing the bounds of their types from bounded to unbounded. There were some changes that needed to be made in this commit in order to make this migration work.
=> fix: support for migrating from bounded type to unbounded type.

src/btreemap.rs, src/btreemap/node.rs, src/btreemap/proptests.rs
BtreeMap will support deque after this PR #106.
And more methods for BTreeMap for #87
=> feat: impl pop_last() & pop_first() for BTreeMap

.github/workflows/ci.yml, rust-toolchain.toml, src/log/tests.rs, src/memory_manager.rs, src/storable.rs, src/vec/tests.rs
Rust 1.73 introduces some the `div_ceil` method on integers, which is something we can use to make parts of the code more readable.
=> chore: update rust to 1.73

Cargo.lock, Cargo.toml, bench.yml, benchmarks/benchmark.rs, profiler/src/benchmark.rs
This PR is another step towards transforming our benchmarking logic into a general-purpose tool that others can use.
Rather than hard-coding everything in `benchmark.rs`, the configuration is moved into a config file called `bench.yml`.
The eventual goal is to evolve the current benchmarking work into a tool that works like this:
1. User defines a configuration file (e.g. `bench.yml`)
2. User installs our benchmarking tool (e.g. `cargo install canbench`)
3. User can now run benchmarks using cargo (e.g. `cargo canbench`)
Note that users won't need to write any code and the file `benchmark.rs` will soon be completely removed.
=> refactor: add config file for benchmarks

src/btreemap.rs
Removes an outdated precondition that was valid before unbounded support for BTreeMap was introduced.
=> docs: remove outdated precondition

.github/workflows/ci.yml, rust-toolchain.toml, src/btreemap/node/v2.rs, src/lib.rs
Problem:
CI was failing because rust >= 1.74 was required.
Solution:
Upgrade the Rust version.
=> chore: Upgrade Rust version

.github/workflows/ci.yml
The benchmark CI job is failing in the case of PRs from forked repositories such as #197 and #188 due to a permissions issue. This commit fixes the permissions issue.
=> fix: permissions in benchmark CI job

.github/workflows/canbench-post-comment.yml, .github/workflows/canbench_ci_download_artifacts.sh
Due to the way Github Actions are setup for security reasons, canbench comments weren't working for PRs from forked repositories.
Rather than commenting directly from CI, we now add a separate workflow that will be triggered once CI is complete, and that workflow will post the comment.
In a followup PR, the CI itself will be updated to use the workflow we're adding here. It cannot be added in the same PR.
=> fix: canbench post comment in CI from forked repos (part 1)

src/btreemap.rs, src/btreemap/node.rs
Adds a new test case to verify that deallocating the root node is done correctly, even when the root node contains overflow pages.
NOTE: The logic in `btreemap.remove` has been slightly modified to be more understandable, but the functionality remains equivalent.
=> test: BTreeMap: add case for deallocating root node with overflows

.github/workflows/conventional-commits.yml
Printing the PR title can open the door for remote code execution, so this commit removes it to be on the safe side.
=> fix: don't print PR title in github workflow

.github/workflows/conventional-commits.yml
As a follow up to #218 we need to further sanitize by using the intermediate step of using an environment variable to avoid possible script injection attack.
=> fix(ci): Sanitize PR title by using ENV

src/base_vec.rs, src/vec/tests.rs
`BaseVec`, which is the underlying data structure used by `StableVec` and `StableMinHeap` provides a `set` method that allows the caller to change the value of an element at a specified index.
The `set` method used the `memory.write` method, which assumed that there is always enough memory to rewrite the element. This assumption would've been fine if other methods like `push` always allocated the maximum amount of space for every element. Currently though, `push` only allocates the amount needed to store the element that's being pushed.
There are two possible solutions:
1. Modify `push` to always allocate the maximum size of an element.
2. Modify `set` to grow the memory as needed as it's rewriting an element.
This commit implements solution 2, which is both simpler and more performant.
=> fix: grow memory when necessary in `BaseVec::set`.

Cargo.lock, Cargo.toml, examples/Cargo.lock
Prepares a new release to include a fix to `BaseVec`.
=> chore: bump version to 0.6.5

Cargo.lock, Cargo.toml, canbench_results.yml
The latest version of canbench is:
* significantly faster to execute, as the replica isn't restarted when running each benchmark.
* more accurate, as it contains more up to date pricing and is now running the benchmark using an app subnet, not a system subnet.
=> chore: upgrade canbench from 0.1.1 to 0.1.7

benchmarks/src/btreemap.rs, canbench_results.yml, src/btreemap.rs, src/btreemap/iter.rs, src/btreemap/proptests.rs
This adds the ability to iterate a `StableBTreeMap` in either direction.
We have been using this within OpenChat for a few weeks now with no issues.
=> feat: implement `DoubleEndedIterator` for `StableBTreeMap`

benchmarks/src/btreemap.rs, canbench_results.yml
Later PRs will optimize these scenarios.
=> test: Add two new benchmarks for benchmarking situations where not every value is read

canbench_results.yml, src/btreemap.rs, src/btreemap/iter.rs, src/btreemap/node.rs, src/btreemap/node/tests.rs, src/btreemap/node/v1.rs, src/btreemap/node/v2.rs
This PR refactors the internal Value data structure that is used to hold a loaded or an unloaded map value. Previous we had stored `Rc<Enum>`-s where `Enum` was either a loaded value (`Vec<u8>`) or an unloaded value (`offset: Bytes`). The new representation stores a `OnceCell` inside the enum so we no longer need `Rc`.
The new representation makes it possible to hand out plain references to the loaded values (whereas a special `Ref` wrapper was necessary previously). Using this, we can optimize some of the code paths leading to good performance gains.
=> perf: Refactor the internal Value data structure and make some performance improvements

canbench_results.yml, src/ic0_memory.rs
These are small methods and hinting the compiler to inline them results in some nice performance gains.
=> perf: Add inline hint to Ic0StableMemory methods

canbench_results.yml, src/base_vec.rs, src/btreemap/node.rs, src/btreemap/node/io.rs, src/btreemap/node/v1.rs, src/btreemap/node/v2.rs, src/cell.rs, src/ic0_memory.rs, src/lib.rs, src/log.rs, src/memory_manager.rs, src/tests.rs, src/vec_mem.rs
I found that a source of significant performance loss is the read method of `Memory`. The `read` method takes a mutable buffer which it fills with values read from the stable memory. According to Rust rules, the buffer passed to read must be initialized before it's passed to read (buffers containing uninitialized values are unsound and can cause UB).
The usual pattern is to create a properly sized Vec, eg. by using `vec![0; size]` or `vec.resize(size, 0)` and pass that to `read`. However, initializing the bytes with values that get overwritten by `read` is only necessary in order to be sound and requires significant number of instructions.
This PR introduces a new method `read_unsafe` which allows passing in a raw pointer and a `count` parameter. Implementations can be more efficient by …
=> perf: Add new efficient APIs read_unsafe and read_to_vec

src/base_vec.rs, src/vec/tests.rs
There is a bug in the current implementation that returns the count until the end of the vector even if some elements have been taken from the iterator using `next_back()` (see the testcase in the PR).
=> fix: Fix Vec Iter::count() after next_back()

canbench_results.yml, rust-toolchain.toml
A transitive dependency (cargo-platform) has been updated and now requires min Rust version 1.78.
Our library can still be used with a lower Rust version but our tests/benchmarks will be run with 1.78.
=> chore: Bump Rust version to 1.78 in rust-toolchain

benchmarks/src/btreemap.rs, benchmarks/src/vec.rs, canbench_results.yml
Also fix the 10mb benchmark, previously we added 200 10**kb** values, now we'll add 20 10**mb** values (like the benchmark description says). 200 10mb values crash the benchmark so let's stick with 20.
=> test: Add a few new benchmarks that exercise the MemoryManager which is often how StableStructures are used

canbench_results.yml, src/memory_manager.rs, src/types.rs
Since buckets are quite big (minimum 64kb and 8MB by default), subsequent accesses will likely touch the same bucket. It's worth caching the last accessed bucket.
=> perf: Add bucket cache in MemoryManager

benchmarks/src/btreemap.rs, canbench_results.yml, src/btreemap.rs
This PR improves performance of `contains_key` by not deserialising the value after finding the entry.
```
---------------------------------------------------
Benchmark: btreemap_contains_key_blob_4_1024
total:
instructions: 166.00 M (improved by 9.69%) 🟢
heap_increase: 0 pages (no change)
stable_memory_increase: 0 pages (no change)
---------------------------------------------------
Benchmark: btreemap_contains_key_blob_4_1024_v2
total:
instructions: 246.60 M (improved by 8.10%) 🟢
heap_increase: 0 pages (no change)
stable_memory_increase: 0 pages (no change)
---------------------------------------------------
```
=> perf: improve contains_key performance

scripts/ci_run_benchmark.sh, src/btreemap.rs
This PR adds emojis to top-level canbench summary the same way it's done in [bitcoin-canister](https://github.com/dfinity/bitcoin-canister/blob/164a18241db834f49770e423d9cccfc4deb45cf5/scripts/canbench_ci_run_benchmark.sh#L77) repo.
It also adds to canbench report a commit hash & time of the benchmark run.
Testing [example log](https://github.com/dfinity/stable-structures/actions/runs/14329924031/job/40163575581#step:6:391).
=> ci: add emojis for visualization to top-level canbench summary

src/btreemap.rs, src/btreemap/node.rs
This PR includes non-functional cleanup changes to improve code readability in upcoming PRs. 
No functionality has been altered.
**Changes:**
- Renamed two similar `save` methods to `save_header` and `save_node`
- Grouped node management methods (allocate/deallocate, load/save) together
- Updated function doc comments for better hover info
=> chore: btreemap code cleanup

.gitignore, src/btreemap.rs, src/btreemap/proptests.rs
Run each `BTreeMap` test for multiple key/value type pairs (bounded and unbounded) by using `btree_test!` macro.
No functional changes, only test code is modified.
Changes:
- add `Build` trait to generate key/value types from `u32` value in monotonic way
- add `btree_test!` macro to run each test on a set of key/value pairs (bounded/unbounded, set-like, map-like)
- add unified key/value helpers to abstract the actual type and improve readability of each test by using `key(i)`/`value(i)` instead of `b(&[1,2,3])`
Before:
```rs
assert_eq!(btree.insert(b(&[1,2,3]), b(&[4,5,6])), None);
assert_eq!(btree.get(&b(&[1,2,3])), Some(b(&[4,5,6])));
assert_eq!(
btree.range(b(&[1, 5])..=b(&[2, 6])).collect::<Vec<_>>(),
vec![
(b(&[1, 6]), b(&[])),
(b(&[1, 8]), b(&[])),
(b(&[1, 10]), b(&[])),
(b(&[2, …
```
=> test: add multi‑type key/value support to BTreeMap tests

.github/workflows/ci.yml, .github/workflows/pages.yml, README.md
This commit updates CI to publish the stable structures book (verified to work: https://dfinity.github.io/stable-structures/). It also updates the README to link to the book.
=> feat: publish stable structures book to github pages

.github/workflows/canbench-post-comment.yml, .github/workflows/ci.yml, .github/workflows/conventional-commits.yml, .github/workflows/pages.yml, Cargo.lock, Cargo.toml, benchmarks/Cargo.toml, canbench_results.yml, scripts/ci_run_benchmark.sh
This PR updates `canbench` version to 0.1.11 and recalculates `canbench_results.yml` reference file.
This is a preparation PR before bumping `canbench` version to 0.1.12 where summary and CSV reports are introduced.
It also formats CI yaml files.
=> chore: update canbench-rs to 0.1.11

Cargo.lock, Cargo.toml, benchmarks/Cargo.toml
This is a left-over after https://github.com/dfinity/stable-structures/pull/304.
=> chore: update rust dependencies to canbench v0.1.14

Cargo.toml, benchmarks/Cargo.toml, canbench_results.yml, src/btreemap.rs, src/btreemap/node/v1.rs, src/btreemap/node/v2.rs
This PR introduces an optional `bench_scope` feature for stable-structures.
When enabled, it adds `canbench_rs` scopes to selected functions.
The feature is disabled by default to avoid overhead during benchmarking.
This allows benchmarking with or without internal measurement code.
CSV report in [google sheets](https://docs.google.com/spreadsheets/d/1NVM109cRXk1DmBf_ry_4XhDGdYHx8L8nf2GtV5ruZ6E/edit?usp=sharing)
=> feat: add optional bench_scope feature for stable-structures

canbench_results.yml, src/btreemap.rs, src/btreemap/node.rs, src/btreemap/node/io.rs, src/btreemap/node/v1.rs, src/btreemap/node/v2.rs
This PR refactors the codebase to prepare for lazy key loading.
- Introduces a shared `LazyObject` structure for both keys and values
- Unifies the API with methods like `get_key` / `get_value`, `key` / `value`, and upcoming `extract_key` / `extract_value`
The refactoring does not change functionality, but introduces a minor performance regression. 
This is due to switching from direct key reads to indexed access, aligning with the future lazy-loading model.
```
instructions:
status:   No significant changes detected 👍
counts:   [total 304 | new 0 | improved 0 | regressed 0 | unchanged 304]
change:   [min -440.00K | med +954.31K | max +79.11M]
change %: [min -0.18% | med +0.11% | max +1.81%]
```
The implementation is split into two parts (refactoring and actual feature) to isolate and …
=> refactor: prepare for lazy key loading

canbench_results.yml, src/storable.rs, src/storable/tuples.rs
Add the `#[inline]` attribute to the `from_bytes` method in all `Storable` trait implementations.
The motivation is that it's usually known at the call site what `Cow` variant is being passed (owned or borrowed). By inlining, the compiler can optimize for the passed `Cow` variant.
=> perf: Inline from_bytes

.github/workflows/ci-notify-slack.yml
This PR fixes the slack notification bot to only push a notification when the PR is opened (not as a draft) or marked as ready for review. In particular, no notifications are pushed when individual reviewers are asked for a review.
=> fix: do not trigger slack notification upon adding reviewers

.github/workflows/pages.yml
currently https://dfinity.github.io/stable-structures/html needs to be accessed instead of the in the readme advertised URL https://dfinity.github.io/stable-structures
I expect this change to fix this.
=> fix: gh pages publish dir

canbench_results.yml, src/btreemap.rs, src/btreemap/iter.rs, src/btreemap/node.rs, src/btreemap/node/v1.rs, src/btreemap/node/v2.rs
This PR enables lazy key loading in `BTreeMap` for large keys.
Keys larger than a fixed threshold are now loaded lazily, reducing unnecessary memory reads. Smaller keys are still loaded eagerly for performance. After benchmarking various thresholds (4, 8, 16, 32, 64 bytes), 16 bytes was found to offer the best balance between performance and overhead.
Detailed benchmark results are available in [this CSV report](https://docs.google.com/spreadsheets/d/1tVRi245U-zAIXK9BMhKORJlyf0YWpeuwTUlnl-U-ET0/edit)
=> feat: add lazy loading for large BTreeMap keys

Cargo.toml
This PR fixes the benchmarks dependencies when used with `bench_scope` feature flag.
=> fix: fix dependency for bench_scope feature in benchmarks

benchmarks/btreemap/src/main.rs, benchmarks/src/common.rs, src/storable.rs
This PR refactors the code by renaming the `FixedVec` type to `UnboundedVecN` and updates all corresponding references in both the storable module and benchmark tests.
=> refactor: rename FixedVec to UnboundedVecN

Cargo.toml
This PR fixes `default-features is ignored` compilation warning.
Before [log](https://github.com/dfinity/stable-structures/actions/runs/15302670009/job/43047459951#step:6:316)
```
+ canbench --less-verbose --hide-results --show-summary --csv
~/work/stable-structures/stable-structures/benchmarks/vec ~/work/stable-structures/stable-structures
warning: /home/runner/work/stable-structures/stable-structures/Cargo.toml: `default-features` is ignored for ic_principal, since `default-features` was not specified for `workspace.dependencies.ic_principal`, this could become a hard error in the future
Finished `release` profile [optimized] target(s) in 0.04s
+ cp ./canbench_results.csv /tmp/canbench_results_vec.csv
```
After [log](https://github.com/dfinity/stable-structures/actions/runs/15388993829/j …
=> chore: fix compilation warning

src/btreemap.rs, src/btreemap/node.rs
This PR optimizes the value update mechanism in BTreeMap by introducing a dedicated method for replacing values without touching the keys.
=> perf: optimize value swap in BTreeMap

docs/src/concepts/memory-trait.md, src/lib.rs
This PR documents that `Memory` trait methods panic or trap on out-of-bounds access.
=> docs: update Memory trait documentation

.github/workflows/ci-notify-slack.yml
This PR updates the Slack notification workflow to escape special characters `&`, `<` and `>`.
https://api.slack.com/reference/surfaces/formatting#escaping
=> ci: sanitize PR name in Slack notification messages like <&test>

benchmarks/btreemap/canbench_results.yml, benchmarks/btreeset/canbench_results.yml, src/btreemap/iter.rs
This PR replaces the use of reference-counted `Rc<Node>` pointers with unique `Box<Node>` allocations in the `BTreeMap` iterator to reduce overhead.
btreemap
```
instructions:
status:   Improvements detected 🟢
counts:   [total 285 | regressed 0 | improved 9 | new 0 | unchanged 276]
change:   [max 0 | p75 -97.33K | median -147.22K | p25 -481.26K | min -5.34M]
change %: [max 0.00% | p75 -0.02% | median -0.03% | p25 -0.06% | min -3.25%]
```
btreeset
```
instructions:
status:   Improvements detected 🟢
counts:   [total 100 | regressed 0 | improved 2 | new 0 | unchanged 98]
change:   [max +625.36K | p75 -288 | median -27.44K | p25 -80.94K | min -377.91K]
change %: [max +0.05% | p75 -0.07% | median -0.30% | p25 -1.17% | min -2.35%]
```
Previous change …
=> perf: use Box<Node> instead of Rc<Node> in BTreeMap iterator

.github/workflows/ci.yml, scripts/ci_run_benchmark.sh
This PR renames references from “main” to a generic “baseline” branch to support custom benchmark baselines.
=> ci: rename 'main' to 'baseline' to support custom benchmark branches

.github/workflows/ci.yml, benchmarks/Cargo.toml, benchmarks/io_chunks/canbench.yml
This PR re-enables `io_chunks` benchmark in the CI.
This is a follow-up PR after https://github.com/dfinity/stable-structures/pull/368.
=> ci: re-enable io_chunks benchmark

.github/workflows/ci.yml
This PR re-enables `nns` benchmark in the CI.
This is a follow-up PR after https://github.com/dfinity/stable-structures/pull/371.
=> ci: enable nns benchmarks

.github/workflows/ci.yml, .github/workflows/pages.yml, rust-toolchain.toml, scripts/ci_run_benchmark.sh
This PR uploads persisted `canbench_results.yml` files as CI artifacts and centralizes Rust toolchain version management across all CI jobs.
This avoids the need to have the exact local environment for calculating `canbench_results.yml` file.
It also centralizes the Rust toolchain version across all CI jobs by introducing a single `RUST_VERSION` variable and updating existing steps to use it.
=> ci: upload persisted canbench_results.yml file

RELEASE_GUIDE.md
This PR adds release guide documentation.
=> docs: add release guide

src/log.rs, src/log/tests.rs
- Provide convenient accessors for the first and last log entries.
- Implemented first(&self) -> Option<T> returning self.get(0).
- Implemented last(&self) -> Option<T> returning the last entry or None when empty.
- Both are inlined and O(1) complexity.
- first/last preserve existing retrieval semantics and types.
- last handles empty logs safely by early None.
updated tests accordingly
=> feat(log): add first() and last() methods
